title: <p align="center"> Anto Thomson George </p>
logo: /assets/img/Anto_Thomson.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
